"For Plugins!
"https://github.com/sainnhe/everforest/blob/master/doc/everforest.txt
call plug#begin('~/.vim/plugged')

Plug 'rakr/vim-one'

Plug 'sainnhe/everforest'

call plug#end()

"Terminal Color Schemes
"https://mayccoll.github.io/Gogh/

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

"Lets me see number on the sides
"set number


"FOR COLORSCHEME EVERFOREST!!!!!
if has('termguicolors')
    set termguicolors
endif
" For dark version.
"set background=dark
"Used for itallics, 1 = true, 0 = flase
let g:everforest_enable_italic = 1
" For light version.
"set background=light
" Set contrast.
" This configuration option should be placed before `colorscheme everforest`.
" Available values: 'hard', 'medium'(default), 'soft'
let g:everforest_background = 'hard'
colorscheme everforest
set background=dark

"FOR COLORSCHEME VIM-ONE!!!!!!!
"let g:airline_theme='one'
