"My vimrc setting will go here for later use

"Get to vim colors
"/usr/share/vim/vim81/colors


"Vim Settings
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

"Lets me see number on the sides
"set number

