# Colors
LPURPLE='\[\e[1;35m\]'  #Light purple
DRED='\[\e[0;31m\]'     #Dark red
CBLUE='\[\e[0;36m\]'    #Cyan Blue
UNKNOWN='\[\e[0;32m\]'  # Don't know
END='\[\e[m\]'
check_fail ()
{
if [ $? = 0 ];
then
    echo -e '\[\e[1;32m\]$\[\e[m\]'
else
    echo -e 'not'
    echo -e '\[\e[1;31m\]$\[\e[m\]'
fi
}
PS2="[\033[01;31m]>[\033[01;33m]>[\033[01;32m]>[\033[0m] "
alias ls='ls -F -G --color'
export PROMPT_DIRTRIM=2 # Trims the directory sturcture to 2
PS1="${LPURPLE}Samuel-Blanco${END}${DRED}:${END}${CBLUE}\w${END}`check_fail $` "


